export const CONTACTS_CREATE_REQUEST = 'CONTACTS_CREATE_REQUEST';
export const CONTACTS_CREATE_SUCCESS = 'CONTACTS_CREATE_SUCCESS';
export const CONTACTS_CREATE_FAIL = 'CONTACTS_CREATE_FAIL';
export const CONTACTS_CREATE_RESET = 'CONTACTS_CREATE_RESET';

export const CONTACTS_LIST_REQUEST = 'CONTACTS_LIST_REQUEST';
export const CONTACTS_LIST_SUCCESS = 'CONTACTS_LIST_SUCCESS';
export const CONTACTS_LIST_FAIL = 'CONTACTS_LIST_FAIL';