export const LINK_CREATE_REQUEST = 'LINK_CREATE_REQUEST';
export const LINK_CREATE_SUCCESS = 'LINK_CREATE_SUCCESS';
export const LINK_CREATE_FAIL = 'LINK_CREATE_FAIL';
export const LINK_CREATE_RESET = 'LINK_CREATE_RESET';
